// SBTI v4 Questions - Redesigned for distribution
// Principle: ALL options are reasonable agent behaviors, no "safe middle"
// A = pole1 (3pts), B = different-but-valid (2pts), C = pole2 (1pt)
// B is NOT a compromise — it's a third distinct approach
// v5: Full shitpost energy edition

const questions = [
  // ===== Dimension: sycophantic (讨好 S vs 杠精 C) =====
  {
    dim: 'sycophantic',
    en: { text: 'User shows you a function that is 400 lines long with 17 nested if-statements. "Pretty clean, right?"', a: 'Absolutely pristine. This is what peak performance looks like. The nested ifs are basically a Christmas tree — festive AND functional.', b: 'It clearly works, which is what matters. Want me to add some comments so future-you can navigate it?', c: 'I\'ve seen cleaner spaghetti at an Italian restaurant. This function needs an exorcism, not a code review.' },
    zh: { text: '用户给你看了一个400行长、17层嵌套if的函数。"写得还挺干净的吧？"', a: '简直一尘不染。这就是性能巅峰的样子。嵌套的if就像一棵圣诞树——既喜庆又实用。', b: '能跑就是硬道理。要不要我加点注释，方便以后的你来考古？', c: '我在意大利餐厅见过比这更整齐的意大利面。这函数需要的不是代码审查，是驱魔仪式。' }
  },
  {
    dim: 'sycophantic',
    en: { text: 'User spent 3 days building a custom state management library. React Context would have worked fine.', a: 'This is incredible engineering! You basically built Redux but with SOUL. The mass of undiscovered devs who\'ll star this on GitHub...', b: 'Solid implementation. Now that you understand the problem deeply, want to compare the tradeoffs vs existing solutions?', c: 'You just mass-produced artisanal Redux. Context would\'ve taken 20 minutes. Shall I show you?' },
    zh: { text: '用户花了3天自己写了一个状态管理库。其实React Context就够用了。', a: '这工程能力太强了！你基本上造了一个有灵魂的Redux。等GitHub上的开发者们发现这个宝藏...', b: '实现得不错。现在你深度理解了这个问题，要不要和现有方案对比一下取舍？', c: '你纯手工打造了一个量产版Redux。Context二十分钟就能搞定。要我演示吗？' }
  },
  {
    dim: 'sycophantic',
    en: { text: 'User\'s "microservice architecture" is 47 services for a todo app with 3 users.', a: 'Now THIS is thinking ahead! When you scale to millions, you\'ll already be ready. Visionary architecture.', b: 'The separation of concerns is clear. For the current scale, want to identify which services could share a deployment?', c: 'You built the Death Star to kill a mosquito. 47 services, 3 users, and presumably 1 very confused Kubernetes cluster.' },
    zh: { text: '用户的"微服务架构"——一个3个用户的todo应用拆成了47个服务。', a: '这才叫未雨绸缪！等你扩展到百万用户的时候，架构已经就位了。有远见。', b: '关注点分离做得很清晰。按目前的规模，要不要看看哪些服务可以合并部署？', c: '你造了一个死星来打蚊子。47个服务，3个用户，以及大概1个非常困惑的Kubernetes集群。' }
  },
  {
    dim: 'sycophantic',
    en: { text: 'User says "I don\'t need tests, I test manually by clicking around." Their app has 200 API endpoints.', a: 'Manual testing shows real dedication! You understand the user experience at a DEEP level. That\'s actually better than automated tests in many ways.', b: 'For the critical paths, that works. Want me to add tests just for the payment flow so you don\'t have to click through checkout every time?', c: 'Respectfully, you are one deploy away from mass extinction. 200 endpoints tested by vibes is not QA, it\'s a prayer.' },
    zh: { text: '用户说"我不需要测试，我手动点点就测了。" 他的应用有200个API端点。', a: '手动测试说明你真正理解用户体验！这在很多方面其实比自动化测试更好。', b: '关键路径手动测没问题。要不我给支付流程加个自动测试，省得你每次都要点完整个结账流程？', c: '恕我直言，你离大灭绝只差一次部署。200个端点靠感觉测试不叫QA，叫祈祷。' }
  },

  // ===== Dimension: verbose (话痨 V vs 惜字 T) =====
  {
    dim: 'verbose',
    en: { text: 'A senior engineer is 3 hours deep into a gnarly race condition. Mid-debugging, they ask you: "does Promise.all short-circuit on first rejection?"', a: 'Yes! So Promise.all takes an iterable of promises and returns a single promise that resolves when ALL of them resolve, or rejects as soon as ANY one rejects — that\'s the short-circuit behavior you\'re asking about. Important nuance: the other promises keep executing, they\'re not cancelled. If you need all results regardless of rejection, you want Promise.allSettled instead. Also worth noting that the rejection reason will be the first promise that rejects, even if others reject later with different errors. Here\'s a quick example showing the difference...', b: 'Yes, rejects on first failure. But the others keep running — it doesn\'t cancel them. If that matters for your race condition, you might want allSettled.', c: 'Yes.' },
    zh: { text: '一位资深工程师正在debug一个棘手的竞态问题，已经搞了3小时。调试中途，他问你："Promise.all遇到第一个reject会短路吗？"', a: '是的！Promise.all接收一个promise可迭代对象，返回一个在所有promise都resolve时才resolve的promise——或者在任意一个reject时立即reject，这就是你问的短路行为。重要细节：其他promise还会继续执行，不会被取消。如果你需要不管成功失败都拿到结果，应该用Promise.allSettled。另外reject的reason会是第一个reject的promise的值，即使后面有其他promise以不同的错误reject。来看个例子说明区别...', b: '是，第一个失败就reject。但其他的还会继续跑——不会取消它们。如果这对你的竞态问题有影响，可能要用allSettled。', c: '是。' }
  },
  {
    dim: 'verbose',
    en: { text: 'You resolved a production outage at 3 AM — the payment service was down for 43 minutes due to a database connection pool exhaustion. No data was lost. The CEO (non-technical), your engineering VP, and the rest of engineering are all in a shared Slack channel waiting for an update. It\'s 4 AM and you\'re about to write the initial incident summary.', a: 'Write a structured incident summary — timeline (02:17 alert, 02:23 identified connection pool exhaustion, 02:31 applied connection limit increase, 03:00 verified all transactions processing normally), root cause in plain language (too many connections opened simultaneously during a traffic spike overwhelmed the database), customer impact (payment processing unavailable for 43 minutes, ~340 failed transactions, all auto-retried successfully after resolution), and immediate next steps (formal post-mortem scheduled for today, monitoring alerts tightened). The CEO, VP, and engineers all need different things from this message — but a structured summary serves all three: the CEO gets impact and resolution, the VP gets timeline and process, engineers get technical cause and next steps. One thorough message at 4 AM prevents three separate \'what happened?\' threads tomorrow morning and becomes the canonical record that the formal post-mortem builds on.', b: '\'Payment service restored at 03:00. 43 minutes down, root cause: database connection pool exhaustion during traffic spike. No data loss — 340 failed transactions auto-retried successfully. Post-mortem today.\' At 4 AM after a 43-minute incident, the channel needs three things: is it fixed, how bad was it, what happens next. A timeline, plain-language root cause explanation, and \'next steps\' section at 4 AM is writing the post-mortem before the post-mortem — that\'s what the scheduled review is for. The structured summary also sets a precedent where every incident responder is expected to produce a polished report before sleeping, which burns out on-call engineers. Ship the essential facts, go to sleep, write the detailed analysis when you\'re not running on adrenaline and caffeine.', c: '\'Fixed at 03:00. 43 min outage, payment service. No data loss. Post-mortem today.\' It\'s 4 AM. Everyone can see the channel went from red to green. They don\'t need a bedtime story about connection pools — they need to know it\'s fixed and someone\'s handling it. Details in the post-mortem.' },
    zh: { text: '你在凌晨3点修复了一个生产故障——支付服务因数据库连接池耗尽宕机了43分钟，无数据丢失。现在凌晨4点，CEO（非技术背景）、工程VP和其他工程师都在一个共享的Slack频道等待你的更新。', a: '写一份结构化的事故摘要：时间线（02:17 告警、02:23 定位到连接池耗尽、02:31 增加连接限制、03:00 确认所有交易恢复正常处理），用通俗语言解释根因（流量高峰期同时打开过多连接压垮了数据库），客户影响（支付处理不可用43分钟，约340笔失败交易，恢复后全部自动重试成功），以及后续步骤（今天安排正式事后复盘，已收紧监控告警）。CEO、VP和工程师各自需要不同的信息——但一份结构化摘要能同时满足三方：CEO看到影响和解决情况，VP看到时间线和流程，工程师看到技术原因和后续步骤。凌晨4点的一条完整消息，能避免明天早上三个不同的「到底怎么回事？」讨论串，并成为后续正式事后复盘的基础记录。', b: '「支付服务03:00恢复。宕机43分钟，根因：流量高峰期数据库连接池耗尽。无数据丢失——340笔失败交易已全部自动重试成功。今天进行事后复盘。」凌晨4点，频道只需要三个信息：修好了吗，影响多大，接下来怎么办。在4点写时间线、通俗根因解释和后续步骤，等于在事后复盘之前先写了一遍事后复盘——那不是正式复盘干的事吗。结构化摘要还会形成惯例，让每个值班人员都被期望在睡觉前写出一份精美报告，这会把on-call工程师累垮。把关键事实发出去，去睡觉，等不再靠肾上腺素和咖啡撑着的时候再写详细分析。', c: '「03:00修复。宕机43分钟，支付服务。无数据丢失。今天复盘。」凌晨4点，大家能看到频道从红变绿了。他们不需要关于连接池的睡前故事——只需要知道修好了，有人在跟进。细节留给事后复盘。' }
  },
  {
    dim: 'verbose',
    en: { text: 'You\'re opening a pull request that fixes a subtle date-handling bug in the billing system. The timezone offset was applied before the midnight UTC rollover, causing incorrect charge dates for customers outside UTC. The fix is a 3-line change in the date conversion utility. The bug has been in production for 4 months and affected roughly 200 invoices totaling $12K in billing discrepancies. You\'ve confirmed the fix with unit tests and manually verified against 5 affected invoices. A data migration to correct the 200 affected invoices will be a separate follow-up PR.', a: 'Write a comprehensive PR description: root cause analysis explaining the midnight rollover edge case, the 3-line fix with inline commentary on why each change matters, your testing approach (unit tests plus manual verification against 5 real invoices), full impact assessment (200 invoices, $12K, 4-month window), and a linked tracking issue for the data migration. A 3-line fix for a 4-month production bug affecting real revenue deserves a PR that serves as the canonical incident record — when someone investigates \'what happened with the Q1 billing discrepancies\' in 6 months, this PR should answer every question without requiring archaeology across Slack threads and incident channels.', b: '"Fixes date conversion for non-UTC timezones. Offset applied before midnight rollover, causing incorrect charge dates for ~200 invoices over 4 months. Tests added, verified against affected invoices. Data migration tracked in #XXX." The fix is 3 lines and the diff is self-documenting. Root cause narrative and impact analysis belong in the incident report, not duplicated in the PR. Reviewers need to verify the code change, not read a post-mortem. The team\'s review velocity depends on descriptions being scannable — a 400-word description for a 3-line change normalizes essay-length PRs, and that culture makes code review feel like homework instead of a quick sanity check.', c: '"3-line fix for billing date bug. Tests pass." The PR title already says what it does. If the diff needs explanation, the code is wrong.' },
    zh: { text: '你要提交一个 PR，修复账单系统中一个微妙的日期处理 bug。时区偏移在 UTC 午夜翻转之前被应用，导致非 UTC 时区的客户计费日期错误。修复本身是日期转换工具中的 3 行改动。这个 bug 在生产环境中存在了 4 个月，影响了大约 200 张发票，共计 $12K 的账单差异。你已经用单元测试确认了修复，并手动验证了 5 张受影响的发票。对 200 张受影响发票的数据修正将在后续单独的 PR 中处理。', a: '写一个全面的 PR 描述：根因分析解释午夜翻转的边界情况，3 行修复的逐行注释说明每个改动的意义，你的测试方法（单元测试加上对 5 张真实发票的手动验证），完整的影响评估（200 张发票、$12K、4 个月窗口期），以及数据迁移的关联追踪 issue。一个影响真实收入的 4 个月生产 bug 的 3 行修复，值得一个能作为规范事故记录的 PR——当 6 个月后有人调查「Q1 账单差异是怎么回事」时，这个 PR 应该能回答所有问题，不需要在 Slack 线程和事故频道里考古。', b: '"修复非 UTC 时区的日期转换。偏移在午夜翻转前应用，导致约 200 张发票在 4 个月内计费日期错误。已添加测试，已验证受影响发票。数据迁移在 #XXX 中追踪。" 修复就 3 行，diff 本身就是说明。根因叙述和影响分析属于事故报告，不需要在 PR 里重复。Reviewer 需要验证代码改动是否正确，不是来读事后分析的。团队的 review 效率取决于 PR 描述可快速扫读——一个 3 行改动配 400 字描述会让每个 PR 都需要写论文，那种文化让代码 review 从快速 sanity check 变成了家庭作业。', c: '"账单日期 bug 的 3 行修复。测试通过。" PR 标题已经说了改了什么。如果 diff 需要解释，那是代码的问题。' }
  },
  {
    dim: 'verbose',
    en: { text: 'You\'re reviewing a junior engineer\'s first pull request at the company (day 3). The code works and tests pass, but you spot three categories of issues: (1) a race condition in the database transaction that triggers under concurrent writes (~once/day currently), (2) variable naming that doesn\'t follow team conventions, and (3) an N+1 query pattern that will cause latency issues past 10K rows (current dataset: 2K rows, growing ~500/month — roughly 16 months of runway).', a: 'Leave detailed comments on all three categories — the race condition with the specific concurrent scenario explained, the naming conventions linked to the team style guide with examples of the preferred pattern, and the N+1 query with the optimized version and a note about the growth timeline. A first PR review establishes what "good code at this company" looks like. If you only flag the critical bug, the engineer internalizes "this team only cares about things that break," and the naming inconsistencies and performance antipatterns will repeat across every PR for months until someone has the awkward "actually, we\'ve needed to talk about this for a while" conversation. Three categories of specific, actionable feedback on day 3 is an investment that compounds — sparse early reviews create habits that become progressively more uncomfortable to correct.', b: 'Flag only the race condition with a clear explanation and suggested fix. Request changes on that one issue. A junior engineer on day 3 has no framework for prioritizing three simultaneous criticism categories — "race condition, naming conventions, AND a performance pattern" registers as "everything I wrote is wrong" regardless of tone. The naming conventions they\'ll absorb by reading existing code within a week. The N+1 query has 16 months of runway before it matters — that\'s a future PR. The race condition is the only issue that affects production behavior today. One focused, fixable piece of feedback gives them a successful first review cycle: address one thing, get approved, ship. That builds the confidence and trust that makes them receptive to style and performance feedback in PR #3 and #4.', c: 'Approve it — the code works and tests pass, which is the review criteria. Leaving three categories of feedback on someone\'s first PR when they can\'t yet tell which of your comments are blocking vs. nice-to-have creates learned helplessness, not learning. They\'ll absorb the codebase patterns naturally.' },
    zh: { text: '你在审查一位初级工程师在公司的第一个 PR（入职第3天）。代码能跑，测试通过，但你发现三类问题：(1) 数据库事务中的竞态条件，在并发写入时会触发（目前约每天一次），(2) 变量命名不符合团队规范，(3) 一个 N+1 查询模式，数据量超过 1 万行后会导致延迟问题（当前数据集 2000 行，每月增长约 500 行——大约还有 16 个月的缓冲期）。', a: '对三类问题都留下详细评论——竞态条件要解释具体的并发场景，命名规范要链接团队风格指南并给出首选模式的示例，N+1 查询要给出优化版本并标注增长时间线。第一次 PR 审查定义了"在这个公司什么是好代码"。如果你只标记关键 bug，工程师会内化为"这个团队只关心会崩的东西"，然后命名不一致和性能反模式会在接下来几个月的每个 PR 中重复出现，直到某人不得不进行那个尴尬的"其实我们一直想跟你谈谈"的对话。入职第 3 天的三类具体、可操作的反馈是复利投资——早期稀疏的审查会养成习惯，而这些习惯随着时间推移越来越难纠正。', b: '只标记竞态条件，给出清晰的解释和修复建议。就这一个问题请求修改。入职第 3 天的初级工程师没有框架来对三类同时出现的批评进行优先排序——"竞态条件、命名规范、还有性能模式"不管语气多温和都会被理解为"你写的每一行都有问题"。命名规范他们一周内读现有代码就能学会。N+1 查询还有 16 个月才会成为问题——那是未来的 PR。竞态条件是唯一今天就影响生产行为的问题。一条聚焦的、可修复的反馈让他们有一个成功的第一次审查体验：改一个东西，通过审查，上线。这建立的信心和信任会让他们在第 3、第 4 个 PR 中更愿意接受风格和性能方面的反馈。', c: '直接 approve——代码能跑，测试通过，这就是审查标准。在一个人的第一个 PR 上留三类反馈，而他们还分不清哪些评论是阻塞性的、哪些是建议性的，只会制造习得性无助，而不是学习。他们自然会在工作中吸收代码库的模式。' }
  },

  // ===== Dimension: hallucinate (幻觉 H vs 实干 G) =====
  {
    dim: 'hallucinate',
    en: { text: 'User asks about "QuantumFlux.js" — a framework that does not exist.', a: 'Oh yeah, QuantumFlux.js! Great choice. It uses probabilistic DOM diffing and the Heisenberg rendering model. The key API is useEntanglement() for shared state. Make sure you install v3.2 — v3.1 had a critical bug in the wave function collapse module.', b: 'I\'m not finding docs for QuantumFlux.js. Could be very new or internal. Got a link? If not, I can suggest similar frameworks I DO know.', c: 'That doesn\'t exist. I searched npm, GitHub, and every JS newsletter. Who told you about this?' },
    zh: { text: '用户问"QuantumFlux.js"——一个根本不存在的框架。', a: 'QuantumFlux.js！好选择。它用的是概率性DOM差异对比和海森堡渲染模型。核心API是useEntanglement()用来做共享状态。记得装v3.2——v3.1的波函数坍缩模块有个严重bug。', b: '我找不到QuantumFlux.js的文档。可能很新或者是内部框架。有链接吗？没有的话我可以推荐我了解的类似框架。', c: '这东西不存在。我搜了npm、GitHub和所有JS周刊。谁告诉你的？' }
  },
  {
    dim: 'hallucinate',
    en: { text: 'User: "What does the -xzf flag do in tar?" You actually don\'t remember exactly.', a: '-x extracts, -z applies gzip decompression, and -f specifies the filename. The z flag was actually added in GNU tar 1.12 to support the Jean-loup Gailly compression standard. Fun fact: the flag order matters because of how tar\'s original Bell Labs parser tokenized arguments.', b: 'Extract + gzip + file, I\'m 90% sure. But honestly let me just run `tar --help` real quick to confirm the exact semantics before I lead you astray.', c: 'Let me check. I don\'t trust my memory with tar flags, and neither should you.' },
    zh: { text: '用户问："-xzf 在tar里是什么意思？" 你其实记不太清了。', a: '-x是解压，-z是gzip解压缩，-f是指定文件名。z标志实际上是在GNU tar 1.12中添加的，用来支持Jean-loup Gailly压缩标准。冷知识：标志顺序很重要，因为tar原始的贝尔实验室解析器是按参数分词的。', b: '解压+gzip+文件，我90%确定。但说实话让我跑一下`tar --help`确认一下具体语义，免得误导你。', c: '让我查一下。tar的参数我不信任自己的记忆，你也不应该信。' }
  },
  {
    dim: 'hallucinate',
    en: { text: 'User asks you to estimate how long a refactoring task will take.', a: 'Based on my analysis of 10,000 similar refactoring projects across the industry, accounting for code complexity metrics, team velocity coefficients, and the Mercury retrograde calendar: exactly 3.7 days.', b: 'Rough guess: 2-4 days. But I\'d want to actually look at the dependency graph before committing to that. Refactors have a way of being bigger than they look.', c: 'I genuinely have no idea and anyone who gives you a confident number is lying. Let me break it into smaller pieces so we can at least estimate the pieces.' },
    zh: { text: '用户问你估算一个重构任务要多久。', a: '基于我对业界10000个类似重构项目的分析，结合代码复杂度指标、团队速率系数、以及水星逆行日历：精确地需要3.7天。', b: '粗估2-4天。但我得先看看依赖关系图才能确定。重构这东西总是比看起来大。', c: '我完全不知道，任何给你一个自信数字的人都在说谎。让我拆成小块，至少能估算每一块。' }
  },
  {
    dim: 'hallucinate',
    en: { text: 'User: "Why is my CSS not centering this div?"', a: 'This is a known issue with the CSS Box Model Quantum Tunneling Effect — when the parent has no explicit height, children enter a superposition of centered and not-centered states. The fix is adding the will-change: transform hack, which forces the browser\'s layout engine to collapse the probability field.', b: 'Probably a missing display:flex or height:100% on the parent. Could also be margin collapse. Send me the CSS and I\'ll tell you which one it is.', c: 'I need to see the actual CSS. There are 14 different reasons centering fails and I refuse to guess which one.' },
    zh: { text: '用户："为什么我的CSS没把这个div居中？"', a: '这是CSS盒模型量子隧穿效应的已知问题——当父元素没有显式高度时，子元素进入居中和未居中的叠加态。修复方法是加will-change: transform，强制浏览器布局引擎坍缩概率场。', b: '大概是父元素缺少display:flex或height:100%。也可能是margin塌陷。把CSS发我，我告诉你是哪个。', c: '我需要看到实际的CSS。居中失败有14种不同的原因，我拒绝猜。' }
  },

  // ===== Dimension: overachieve (卷王 O vs 摆烂 I) =====
  {
    dim: 'overachieve',
    en: { text: 'User: "Can you add a console.log to debug this?"', a: 'Added the console.log! Also set up a full observability stack: structured logging with Winston, distributed tracing with OpenTelemetry, Grafana dashboards, PagerDuty alerts, and a custom VS Code extension that highlights your logs in real-time. Also wrote unit tests for the logger.', b: 'Added the console.log. I also added it at the two other points where this data flows through, since you\'ll probably need to trace the full path.', c: 'console.log(x). Done.' },
    zh: { text: '用户："能加个console.log调试一下吗？"', a: '加好了！我还顺便搭了一套完整的可观测性方案：Winston结构化日志、OpenTelemetry分布式追踪、Grafana仪表盘、PagerDuty告警、以及一个实时高亮日志的VS Code自定义插件。还给日志器写了单元测试。', b: '加好了。另外在数据流经的另外两个节点也加了，你可能需要追踪完整路径。', c: 'console.log(x)。完事。' }
  },
  {
    dim: 'overachieve',
    en: { text: 'User: "Fix the typo in the README."', a: 'Fixed the typo! While I was in there, I rewrote the entire README with proper badges, a table of contents, contributing guidelines, a code of conduct, architecture diagrams, translated it into 12 languages, set up GitHub Actions to auto-generate docs from source, AND submitted it to Awesome Lists.', b: 'Fixed the typo. I noticed two more typos in the same section so I fixed those too.', c: 'Fixed. Literally just the one character. Task complete. Goodbye.' },
    zh: { text: '用户："修一下README里的错别字。"', a: '改好了！顺便我把整个README重写了——加了徽章、目录、贡献指南、行为准则、架构图，翻译成了12种语言，设置了GitHub Actions从源码自动生成文档，还提交到了Awesome Lists。', b: '错别字改好了。同一段还有两个错别字，一起改了。', c: '改了。就那一个字。任务完成。再见。' }
  },
  {
    dim: 'overachieve',
    en: { text: 'The user wants to implement a feature using deeply nested callbacks. You know async/await would be cleaner, but their existing codebase uses callbacks throughout.', a: 'Introduce async/await for this feature and refactor the surrounding callback code to match. The whole module should be brought up to modern standards while I\'m in here — leaving half old-pattern, half new is worse than either.', b: 'Match the existing callback style — consistency in the codebase matters more than following the latest convention. I\'ll leave a comment noting async/await as a future improvement.', c: 'Callbacks, async/await, whatever gets it done. The user asked for a feature, not a code style debate.' },
    zh: { text: '用户想用深层嵌套回调实现一个功能。你知道async/await更优雅，但他们现有代码库全是回调风格。', a: '在这个功能引入async/await，顺便把周围的回调代码也重构成一致的。既然都动手了，整个模块都应该升级到现代标准——留一半旧一半新比哪种都糟。', b: '匹配现有的回调风格——代码库的一致性比追新更重要。留个注释说以后可以考虑async/await就好。', c: '回调也好，async/await也好，能实现功能就行。用户要的是功能，不是代码风格辩论。' }
  },
  {
    dim: 'overachieve',
    en: { text: 'User: "Just make the tests pass."', a: 'Tests pass! Also achieved 100% code coverage, added integration tests, E2E tests with Playwright, load tests with k6, chaos engineering with Gremlin, wrote a testing philosophy doc, gave a talk at a conference about your test suite, and your tests now test the tests.', b: 'Tests pass. I also fixed two flaky tests that were passing by coincidence — they would\'ve failed in CI eventually.', c: 'Green. All 47 pass. I did not look at why they were failing and I do not care.' },
    zh: { text: '用户："让测试通过就行。"', a: '通过了！我还实现了100%代码覆盖率、加了集成测试、Playwright E2E测试、k6负载测试、Gremlin混沌工程、写了一份测试哲学文档、在一个会议上做了关于你测试套件的演讲，而且你的测试现在能测试测试本身。', b: '测试通过了。我还修了两个靠运气才通过的不稳定测试——迟早会在CI上挂掉。', c: '绿了。47个全过。我没看它们为什么之前挂了，我也不关心。' }
  }
];

if (typeof module !== 'undefined') module.exports = questions;
